name: Build mosdns

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          check-latest: true

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mosdns-build
          path: './release/mosdns*.zip'
